dev1/demo1/urls.py
from  django.conf.urls import  url

from . import  views

app_name = 'demo1'

urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^list/$',views.list,name='list'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^delete/(\d+)/$',views.delete,name='delete'),
    url(r'^hdelete/(\d+)/$',views.hdelete,name='hdelete'),
    url(r'^addbook/$',views.addbook,name='addbook'),
    url(r'^addbend/$',views.addbend,name='addbend'),
    url(r'^addhero/(\d+)/$',views.addhero,name='addhero'),
    url(r'^addend/$',views.addend,name='addend'),


]

dev1/dev1/urls.py
#项目的URL声明

"""dev1 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from  django.conf.urls import url,include



urlpatterns = [
    path('admin/', admin.site.urls),
    url('demo1/',include('demo1.urls',namespace='demo1')),

]

dev1/demo1/models.py
#与数据库操作相关，存入或读取数据时用到这个，
# 当然用不到数据库的时候 你可以不使用。
from django.db import models

# Create your models here.

class BookInfo(models.Model):
    btitle=models.CharField(max_length=20)
    bpub_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.btitle

    def bname(self):
        return self.btitle

    bname.short_description = '书籍名'

class HeroInfo(models.Model):
    hname=models.CharField(max_length=20)

    hgender=models.BooleanField()

    hcontent=models.CharField(max_length=50)

    #外键 第一个参数为表名  第二个参数代表删除类型
    hbook=models.ForeignKey('BookInfo',on_delete=models.CASCADE)

    def __str__(self):
        return self.hname

    def pname(self):
        return self.hname

    pname.short_description = '人物'

    def sex(self):
        return self.hgender
    sex.short_description = '性别'

    def skill(self):
        return self.hcontent

    skill.short_description = '英雄技能'


'''
定义模型：继承model.Model
配置数据库：默认sqlite
将应用名添加到应用到列表 installed_apps


python manage.py  makemigrations  生成迁移文件

python manage.py  migrate  执行迁移


python manage.py shell 进入命令：不需要运行项目就可以操作数据库
导入类 from demo1.models import HeroInfo，BookInfo
查找所有行 表名.objects.all()
根据主键查找   表名.objects.get(pk=1)
添加对象  **.save()
修改  **.save()

删除 **.delete()


一对多： 一方存在主键   多方存在主键也存在外键（一方中主键）

一方.heroinfo_set.all()
'''

dev1/demo1/views.py
#处理用户发出的请求，从urls.py中对应过来,
# 通过渲染templates中的网页可以将显示内容，
# 比如登陆后的用户名，用户请求的数据，输出到网页。

from django.shortcuts import render,redirect,reverse,get_object_or_404,get_list_or_404

from django.http import HttpResponse,HttpResponseRedirect,JsonResponse

from .models import BookInfo ,HeroInfo

from django.template import loader

# Create your views here.


def index(request):
    # respons={'dasdad':"najnai"}
    # return JsonResponse(respons)
    return render(request,'demo1/index.html',{'username':'lxl'})


def list(request):
    bookInfo=BookInfo.objects.all()
    return render(request,'demo1/list.html',{'lista':bookInfo})


def delete(request,id):
    BookInfo.objects.get(pk=id).delete()
    bookInfo = BookInfo.objects.all()
    return HttpResponseRedirect('/demo1/list/',{'bookk':bookInfo})

def hdelete(request,id):
    name=HeroInfo.objects.get(pk=id).hbook
    HeroInfo.objects.get(pk=id).delete()
    bname=BookInfo.objects.get(btitle=name)

    # return HttpResponse(bname.id)
    return HttpResponseRedirect('/demo1/detail/'+str(bname.id)+'/',{'bname':bname})


def addbook(request):

    return render(request,'demo1/addbook.html')

def addbend(request):
    bname=request.POST['bookname']
    b1=BookInfo()
    b1.btitle=bname
    b1.save()
    return HttpResponseRedirect('/demo1/list/')

def addhero(request,id):
    # book=get_object_or_404(BookInfo,PK=id)
    book=BookInfo.objects.get(pk=id)
    return render(request,'demo1/addhero.html', {'bookk': book})

def addend(request):
    hname=request.POST['username']
    hsex=request.POST['usersex']
    hskill = request.POST['userskill']
    userid=request.POST['userid']
    book=BookInfo.objects.get(pk=userid)
    hero=HeroInfo()
    hero.hname=hname
    if hsex:
        hero.hgender=True
    else:
        hero.hgender=False
    hero.hcontent=hskill
    hero.hbook=book
    print(hname,hsex,hskill,book)
    hero.save()
    return  HttpResponseRedirect('/demo1/detail/'+str(userid)+'/',{'bname':book})



def detail(request,id):
    try:
        name = BookInfo.objects.get(pk=id)
        return render(request, 'demo1/detail.html', {'bname': name})

    except Exception as e:
        print(e)


'''
创建模板文件夹 templates
配置模板目录 os.path.join（BASE_DIR,'templates'）
创建项目模板目录，创建模板


加载模板  temp=loader.get_template（）
使用变量渲染模板  result = temp.render（{}）
返回 HttpRoesponse(result)
'''

dev1/templates/demo1/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>添加书籍</h2>

    <form action="{% url 'demo1:addbend' %}" method="post">
        书籍名称：<input type="text" name="bookname" value="">
        <br>
        <input type="submit" value="添加">
    </form>
    <br>
    <a href="{% url 'demo1:list' %}">返回列表</a>
    <a href="{% url 'demo1:index' %}">回到首页</a>
</body>
</html>

dev1/templates/demo1/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form action="{% url 'demo1:addend' %}" method="post">

        人物名称：<input type="text" name="username" value="">
        人物性别：男<input type="radio" name="usersex" value="1"> 女 <input type="radio" name="usersex" value="0">
        人物绝招：<input type="text" name="userskill" value="">
        <input type="hidden" value="{{bookk.id}}"  name="userid">
        <input type="submit" value="添加">

    </form>



    <a href="{% url 'demo1:detail' bookk.id %}">返回详情</a>
    <a href="{% url 'demo1:list' %}">返回列表</a>
    <a href="{% url 'demo1:index' %}">回到首页</a>


</body>
</html>

dev1/templates/demo1/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>{{bname.btitle}}的详情</h2>
    <ul>
        {% for i in bname.heroinfo_set.all%}

            <li>{{i.hname}}------{{i.hcontent}}
                <a href="{% url 'demo1:hdelete' i.id %}">删除</a>
            </li>

        {% endfor %}

    </ul>
    <a href="{% url 'demo1:addhero' bname.id %}">添加</a>

    <a href="{% url 'demo1:list' %}">返回列表</a>
    <a href="{% url 'demo1:index' %}">回到首页</a>

</body>
</html>

dev1/templates/demo1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static '/css/index.css' %}">
    {#<link rel="stylesheet" href="/static/css/index.css">#}
</head>
<body>
    <div>
        
        {%if username%}
            <h2>{{username}}</h2>
        {%else%}
            <h2>你不在这里</h2>
        {%endif%}
    
        {#超级链接硬编码#}
        {#<a href="/demo1/list/">进入list</a>#}
    
        {#去除硬编码#}
        <a href="{% url 'demo1:list' %}">进入list</a>
    </div>


    <!--<img src="/static/img/111.gif" alt="加载失败">-->
    <img src="{% static '/img/111.gif' %}" alt="加载失败">


</body>
</html>

dev1/templates/demo1/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>书籍名称</h1>
    <ul>

        {% for i in lista %}
            <li><a href="{% url 'demo1:detail' i.id %}">{{i.btitle}}</a>
                <a href="{% url 'demo1:delete' i.id %}">删除</a>
            </li>
        {% empty %}
            <h3>没有书</h3>
        {% endfor %}

    </ul>
    <a href="{% url 'demo1:addbook' %}">添加</a>
    {#<a href="/demo1/">回到首页</a>#}
    <a href="{% url 'demo1:index' %}">回到首页</a>

</body>
</html>